### ISSUE TITLE
Deploy github action

### ISSUE THREAD

**Issue by dennis2311** [dennis2311/Eagloo-newBack#4]
- [x] Deploy build.yml.
- [ ] .env .gitignore에서 제외 (private 적용)

**Comment by rhkdgns95** [comment]
**Todo**
- Vercel deploy 환경설정 완료.
- Type Error 수정.
- 현재  github repo에 vercel에 필요한 아래의 security key를 등록해야함 (@dennis2311)
  ```
  VERCEL_TOKEN
  ORG_ID
  PROJECT_ID
  ```
- vercel 명령어를 통해 로그인 인증완료 후, 터미널창에 `$ vercel` 입력.
